### ISSUE TITLE
Add more cities or states

### ISSUE THREAD

**Issue by TeeeeJay** [real-ali/country_picker_plus#1]
Hello, well i am from lebanon and i can see its missing some cities, how can we fix this.

**Comment by real-ali** [comment]
> Hello, well i am from lebanon and i can see its missing some cities, how can we fix this.

I apologize for realizing it late. I will resolve this issue as soon as possible and make every effort to ensure that all data is complete. Thank you for informing me about it.

**Comment by real-ali** [comment]
> Hello, well i am from lebanon and i can see its missing some cities, how can we fix this.

I apologize for realizing it late. I will resolve this issue as soon as possible and make every effort to ensure that all data is complete. Thank you for informing me about it.

**Comment by TeeeeJay** [comment]
Thank you Ali,
